// Code generated by 'go test'. DO NOT EDIT.

package testing // (main)

import (
	"os"

	"testing"
	"testing/internal/testdeps"

	_test "a"
)

// START OMIT
var tests = []testing.InternalTest{

	{"TestAdd", _test.TestAdd},
}

var benchmarks = []testing.InternalBenchmark{}

var fuzzTargets = []testing.InternalFuzzTarget{}

var examples = []testing.InternalExample{}

func init() {
	testdeps.ImportPath = "a"
}

func main() {

	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

// END OMIT
